# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: TMHS Button Boss
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  For all of your button needs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Customization
header:
  title: TMHS Button Boss
  subtitle: For all of your button needs
  background: /assets/background.jpg # Update with your background image

# Navigation links
nav_links:
  - title: "Home"
    url: "/"
  - title: "Buttons"
    url: "/buttons"
  - title: "About"
    url: "/about"

# Social links
social_links:
  - title: "GitHub"
    url: "https://github.com/TMHSDigital"
    icon: "fab fa-github"
  - title: "Twitter"
    url: "https://twitter.com/jekyllrb"
    icon: "fab fa-twitter"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/background.jpg # Add your custom background image to assets
