name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install Jekyll and Bundler
      run: |
        gem install jekyll bundler

    - name: Build Site
      run: |
        jekyll build

    - name: Test Site
      run: |
        jekyll serve
